config/routes.rb
Club::Application.routes.draw do
  devise_for :members
  devise_scope :member do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'update', to: 'devise/registrations#edit', as: :update
    get 'logout', to: 'devise/sessions#destroy', as: :logout
    get 'recover', to: 'devise/passwords#new', as: :recover
  end

  get 'admin', to: 'admin/members#index'
  namespace :admin do
    resources :members, only: [:index, :edit, :update, :destroy]
  end
  resources :clubhouses

  root 'clubhouses#index'

end

app/models/clubhouse.rb
class Clubhouse < ActiveRecord::Base
  validates :name, :club_president, :veep, :accountant,
            :clerk, :first_permanent_member, :second_permanent_member, :third_permanent_member, presence: true

  has_and_belongs_to_many :members
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :clubhouses

  def name
    first_name + " " +last_name
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_member, only: [:edit, :update, :destroy]
  before_action :ensure_admin

  def index
    @members = Member.all
  end

  def new
    @member = Member.new
  end

  def create

  end

  def edit
    if @member.president
      @member.update_attribute :president, true
    else
      @member.update_attribute :president, false
    end
    update
  end



  def update
    redirect_to admin_member_path, notice: 'Kullanıcı başarıyla güncellendi!' if @member.update(member_params)
  end

  def destroy
    redirect_to admin_member_path, alert: 'Kullanıcı başarıyla silindi!' if @member.destroy
  end

  private

  def set_member
    @member = Member.find(params[:id])
  end

  def member_params
    params.require(:member).permit(:email, :first_name, :last_name, :password, :password_confirmation, :admin, :president)
  end

  def ensure_admin
    redirect_to :root, :alert => "Yetkisiz erişim sağlamaya çalışıyorsunuz!" unless current_member.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/clubhouses_controller.rb
class ClubhousesController < ApplicationController
  before_filter :set_clubhouse, only: [:show, :edit, :update, :destroy]
  def index
  	@clubs = Clubhouse.all
  end

  def show
  end

  def new
  	@club = Clubhouse.new
  end

  def create
    @club = Clubhouse.new(clubhouse_params)
    if @club.save
      redirect_to @club, notice: 'İlan başarıyla oluşturuldu!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @club.update(clubhouse_params)
      redirect_to @club, notice: "başarılı"
    else
      render :edit
    end
  end

  def destroy
    @club.delete
    redirect_to root_path, notice: 'İlan başarıyla silindi!'
  end

  private
  def set_clubhouse
    @club = Clubhouse.find(params[:id])
  end

  def clubhouse_params
    params.require(:clubhouse).permit(:name, :club_president, :veep, :accountant, :clerk, :first_permanent_member, :second_permanent_member, :third_permanent_member)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubhouses_helper.rb
module ClubhousesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/admin/members/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>
      Üyeler
    </h4>
  </div>
  <div class="panel-body">
    <% @members.each do |member| %>
        <div class="col-md-9">
          <strong><%= link_to member.name, admin_path(member) %></strong>

        </div>
        <% if member_signed_in? and (current_member.admin) %>
            <div class="col-md-3 ">
              <% if member.president %>
                  <%= link_to "Başkanlıktan Al", edit_admin_member_path(member), class: "btn btn-default"%> |
              <% else %>
                  <%= link_to "Başkan Yap", edit_admin_member_path(member), class: "btn btn-default"%> |
              <% end %>

              <%= link_to "Sil", admin_member_path(member), method: :delete, data: { confirm: 'Emin misin?' }, class: "btn btn-danger" %>
            </div>
        <% end %>
        <br><br>
    <% end %>

  </div>
</div>
</div>

app/views/clubhouses/edit.html.erb
<div class="panel-body">
  <div class="row">
    <div class="container">
      <%= simple_form_for(@club) do |f| %>
          <%= f.input :name, label: "Başlık:", placeholder: "Lütfen başlık giriniz!" %>

          <%= f.button :submit, "Gönder", :class => "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <hr \>
  <%= link_to "Geri", root_path, :class => "btn btn-sm btn-default"%>
</div>

app/views/clubhouses/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>
      Kulüpler
    </h4>
  </div>
      <div class="panel-body">
        <% @clubs.each do |club| %>
              <div class="col-md-9">
                  <strong><%= link_to club.name, clubhouse_path(club) %></strong>
              </div>
            <% if member_signed_in? and (current_member.admin) %>
              <div class="col-md-3 ">
                  <%= link_to "Düzenle", edit_clubhouse_path(club), class: "btn btn-default"%> |
                  <%= link_to "Sil", club, method: :delete, data: { confirm: 'Emin misin?' }, class: "btn btn-danger" %>
              </div>
            <% end %>
            <br><br>
        <% end %>

      </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <a class="btn btn-primary" data-toggle="modal" href="#myModal" >Login</a>

    <div class="modal hide" id="myModal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Login to MyWebsite.com</h3>
      </div>
      <div class="modal-body">

        <%= simple_form_for login_path do |f| %>
            <div class="form-inputs">
              <%= f.input :email, required: false, autofocus: true %>
              <%= f.input :password, required: false %>
            </div>

            <div class="form-actions">
              <%= f.button :submit, "Log in" %>
            </div>
        <% end %>
      </div>
      <div class="modal-footer">
        New To MyWebsite.com?
        <a href="#" class="btn btn-primary">Register</a>
      </div>
    </div>
  </div>
</div>
<% if member_signed_in? and (current_member.admin) %>
    <%= link_to "Yeni Kulüp Oluştur", new_clubhouse_path, class: "btn btn-success"%>
<% end %>

app/views/clubhouses/new.html.erb
<%= simple_form_for(@club) do |f| %>
    <%= f.input :name, label: "Kulüp İsmi:", placeholder: "Lütfen kulüp ismi giriniz!" %>
    <%= f.input :club_president, label: "Kulüp Başkanı" %>
    <%= f.input :veep, label: "Başkan Yardımcısı" %>
    <%= f.input :accountant, label: "Sayman" %>
    <%= f.input :clerk, label: "Yazman" %>
    <%= f.input :first_permanent_member, label: "1.Asil Üye" %>
    <%= f.input :second_permanent_member, label: "2.Asil Üye" %>
    <%= f.input :third_permanent_member, label: "3.Asil Üye" %>

    <%= f.button :submit, "Oluştur", :class => "btn btn-primary" %>
<% end %>

<hr \>
<%= link_to "Geri", root_path, :class => "btn btn-sm btn-default"%>

app/views/clubhouses/show.html.erb
<%= @club.name %>
<hr \>
<%= link_to "Geri", root_path, :class => "btn btn-sm btn-default"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Club</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand">Ondokuz Mayıs Üniversitesi</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"  id="dropdownMenu1">
                  <% if member_signed_in? %>
                      <span class="glyphicon glyphicon-user"></span> <%= current_member.name %>
                  <% else %>
                      <span class="glyphicon glyphicon-user"></span> Misafir Kullanıcı
                  <% end %>
                <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <% if member_signed_in? %>
                    <% if current_member.admin %>
                        <li><%= link_to "Yönetim Paneli", admin_path %></li>
                    <% end %>
                    <li><%= link_to "Çıkış Yap", logout_path %></li>
                <% else %>
                    <li><%= link_to "Giriş Yap", login_path %></li>
                <% end %>
              </ul>
            </li>
            <li class="active"><%= link_to "Kulüpler", root_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
</body>
</html>